### ISSUE TITLE
我最近也在学习FAT32可以交流以下吗？https://zhouxinwen.top/

### ISSUE THREAD

**Issue by neverdied** [ThousandPine/FAT12_Test#1]

**Comment by neverdied** [comment]
加qq 2893661486或827773490在github上我很少看回复

**Comment by ThousandPine** [comment]
其实issue里的回复是会直接通知到邮箱的，所以其实qq也能收得到。
另外，时隔三个月我也不确定还能掌握多少细节，你可以先把现有的问题都发出来，我看看有哪些能够帮上忙。
